[package]
name = "rust-csv"
version = "0.1.0"
edition = "2021"

[dependencies]
polars = "0.45.1"
reqwest = { version = "0.10", features = ["json"] }
serde = "1.0.217"
tokio = { version = "0.2", features = ["full"] }
